// src/app.ts
import express from "express";

// src/app/config/env.ts
import dotenv from "dotenv";
dotenv.config();
var requiredEnvVars = ["NODE_ENV", "PORT", "DATABASE_URL", "JWT_SECRET"];
requiredEnvVars.forEach((varName) => {
  if (!process.env[varName]) {
    throw new Error(
      `Environment variable ${varName} is required but not set in .env file.`
    );
  }
});
var loadEnvVariables = () => {
  return {
    NODE_ENV: process.env.NODE_ENV,
    PORT: process.env.PORT,
    DATABASE_URL: process.env.DATABASE_URL,
    JWT_SECRET: process.env.JWT_SECRET
  };
};
var envVars = loadEnvVariables();

// src/app/middleware/golbelErrorHandler.ts
import status from "http-status";
var globalErrorHandler = (err, req, res, next) => {
  if (envVars.NODE_ENV === "development") {
    console.log("Error From Global Error Handler:", err);
  }
  let statusCode = status.INTERNAL_SERVER_ERROR;
  let message = "Internal Server Error";
  res.status(statusCode).json({
    success: false,
    message,
    error: err.message
  });
};

// src/app/middleware/notFound.ts
import status2 from "http-status";
var notFound = (req, res) => {
  res.status(status2.NOT_FOUND).json({
    success: false,
    message: `Route ${req.originalUrl} not found`
  });
};

// src/app.ts
import cors from "cors";

// src/app/routes/index.ts
import { Router as Router2 } from "express";

// src/app/modules/user/user.route.ts
import { Router } from "express";

// src/app/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// src/generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// src/generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.4.2",
  "engineVersion": "94a226be1cf2967af2541cca5529f0f7ba866919",
  "activeProvider": "postgresql",
  "inlineSchema": 'model Cart {\n  id String @id @default(uuid())\n\n  userId String\n  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  productId String\n  product   Product @relation(fields: [productId], references: [id], onDelete: Cascade)\n\n  quantity Int @default(1)\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@unique([userId, productId]) // same product duplicate \u09A8\u09BE \u09B9\u09DF\n}\n\nenum Role {\n  CUSTOMER\n  ADMIN\n  SELLER\n}\n\nenum STATUS {\n  ACTIVE\n  INACTIVE\n  BLOCKED\n}\n\nenum OrderStatus {\n  PENDING\n  CONFIRMED\n  SHIPPED\n  DELIVERED\n  CANCELLED\n}\n\nmodel Order {\n  id String @id @default(uuid())\n\n  userId String\n  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  total  Float\n  status OrderStatus @default(PENDING)\n\n  items OrderItem[]\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}\n\nmodel OrderItem {\n  id String @id @default(uuid())\n\n  orderId String\n  order   Order  @relation(fields: [orderId], references: [id], onDelete: Cascade)\n\n  productId String\n  product   Product @relation(fields: [productId], references: [id], onDelete: Cascade)\n\n  name     String // snapshot\n  price    Float // snapshot\n  quantity Int\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}\n\nmodel Product {\n  id          String  @id @default(uuid())\n  name        String\n  slug        String  @unique\n  description String?\n\n  price    Float\n  discount Float?\n  stock    Int    @default(0)\n\n  thumbnail String\n  images    String[]\n\n  brand    String?\n  category String?\n\n  rating      Float @default(0)\n  reviewCount Int   @default(0)\n\n  isFeatured  Boolean @default(false)\n  isPublished Boolean @default(true)\n\n  // Relations\n  orderItems OrderItem[]\n  carts      Cart[]\n  wishlist   Wishlist[]\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}\n\n// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?\n// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../../src/generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nmodel User {\n  id       String  @id @default(uuid())\n  name     String\n  email    String  @unique\n  password String\n  phone    String? @unique\n  avatar   String?\n\n  role   Role   @default(CUSTOMER)\n  status STATUS @default(ACTIVE)\n\n  address String?\n  city    String?\n  country String?\n\n  lastLogin     DateTime?\n  emailVerified Boolean   @default(false)\n  provider      String? // google, email\n\n  // Relations\n  orders   Order[]\n  carts    Cart[]\n  wishlist Wishlist[]\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}\n\nmodel Wishlist {\n  id String @id @default(uuid())\n\n  userId String\n  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  productId String\n  product   Product @relation(fields: [productId], references: [id], onDelete: Cascade)\n\n  createdAt DateTime @default(now())\n\n  @@unique([userId, productId]) // duplicate wishlist prevent\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"Cart":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"CartToUser"},{"name":"productId","kind":"scalar","type":"String"},{"name":"product","kind":"object","type":"Product","relationName":"CartToProduct"},{"name":"quantity","kind":"scalar","type":"Int"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Order":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"OrderToUser"},{"name":"total","kind":"scalar","type":"Float"},{"name":"status","kind":"enum","type":"OrderStatus"},{"name":"items","kind":"object","type":"OrderItem","relationName":"OrderToOrderItem"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"OrderItem":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"orderId","kind":"scalar","type":"String"},{"name":"order","kind":"object","type":"Order","relationName":"OrderToOrderItem"},{"name":"productId","kind":"scalar","type":"String"},{"name":"product","kind":"object","type":"Product","relationName":"OrderItemToProduct"},{"name":"name","kind":"scalar","type":"String"},{"name":"price","kind":"scalar","type":"Float"},{"name":"quantity","kind":"scalar","type":"Int"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Product":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"slug","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"price","kind":"scalar","type":"Float"},{"name":"discount","kind":"scalar","type":"Float"},{"name":"stock","kind":"scalar","type":"Int"},{"name":"thumbnail","kind":"scalar","type":"String"},{"name":"images","kind":"scalar","type":"String"},{"name":"brand","kind":"scalar","type":"String"},{"name":"category","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Float"},{"name":"reviewCount","kind":"scalar","type":"Int"},{"name":"isFeatured","kind":"scalar","type":"Boolean"},{"name":"isPublished","kind":"scalar","type":"Boolean"},{"name":"orderItems","kind":"object","type":"OrderItem","relationName":"OrderItemToProduct"},{"name":"carts","kind":"object","type":"Cart","relationName":"CartToProduct"},{"name":"wishlist","kind":"object","type":"Wishlist","relationName":"ProductToWishlist"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"phone","kind":"scalar","type":"String"},{"name":"avatar","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"Role"},{"name":"status","kind":"enum","type":"STATUS"},{"name":"address","kind":"scalar","type":"String"},{"name":"city","kind":"scalar","type":"String"},{"name":"country","kind":"scalar","type":"String"},{"name":"lastLogin","kind":"scalar","type":"DateTime"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"provider","kind":"scalar","type":"String"},{"name":"orders","kind":"object","type":"Order","relationName":"OrderToUser"},{"name":"carts","kind":"object","type":"Cart","relationName":"CartToUser"},{"name":"wishlist","kind":"object","type":"Wishlist","relationName":"UserToWishlist"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Wishlist":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"UserToWishlist"},{"name":"productId","kind":"scalar","type":"String"},{"name":"product","kind":"object","type":"Product","relationName":"ProductToWishlist"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","user","order","orderItems","carts","product","wishlist","_count","items","orders","Cart.findUnique","Cart.findUniqueOrThrow","Cart.findFirst","Cart.findFirstOrThrow","Cart.findMany","data","Cart.createOne","Cart.createMany","Cart.createManyAndReturn","Cart.updateOne","Cart.updateMany","Cart.updateManyAndReturn","create","update","Cart.upsertOne","Cart.deleteOne","Cart.deleteMany","having","_avg","_sum","_min","_max","Cart.groupBy","Cart.aggregate","Order.findUnique","Order.findUniqueOrThrow","Order.findFirst","Order.findFirstOrThrow","Order.findMany","Order.createOne","Order.createMany","Order.createManyAndReturn","Order.updateOne","Order.updateMany","Order.updateManyAndReturn","Order.upsertOne","Order.deleteOne","Order.deleteMany","Order.groupBy","Order.aggregate","OrderItem.findUnique","OrderItem.findUniqueOrThrow","OrderItem.findFirst","OrderItem.findFirstOrThrow","OrderItem.findMany","OrderItem.createOne","OrderItem.createMany","OrderItem.createManyAndReturn","OrderItem.updateOne","OrderItem.updateMany","OrderItem.updateManyAndReturn","OrderItem.upsertOne","OrderItem.deleteOne","OrderItem.deleteMany","OrderItem.groupBy","OrderItem.aggregate","Product.findUnique","Product.findUniqueOrThrow","Product.findFirst","Product.findFirstOrThrow","Product.findMany","Product.createOne","Product.createMany","Product.createManyAndReturn","Product.updateOne","Product.updateMany","Product.updateManyAndReturn","Product.upsertOne","Product.deleteOne","Product.deleteMany","Product.groupBy","Product.aggregate","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","User.upsertOne","User.deleteOne","User.deleteMany","User.groupBy","User.aggregate","Wishlist.findUnique","Wishlist.findUniqueOrThrow","Wishlist.findFirst","Wishlist.findFirstOrThrow","Wishlist.findMany","Wishlist.createOne","Wishlist.createMany","Wishlist.createManyAndReturn","Wishlist.updateOne","Wishlist.updateMany","Wishlist.updateManyAndReturn","Wishlist.upsertOne","Wishlist.deleteOne","Wishlist.deleteMany","Wishlist.groupBy","Wishlist.aggregate","AND","OR","NOT","id","userId","productId","createdAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","name","email","password","phone","avatar","Role","role","STATUS","status","address","city","country","lastLogin","emailVerified","provider","updatedAt","every","some","none","slug","description","price","discount","stock","thumbnail","images","brand","category","rating","reviewCount","isFeatured","isPublished","has","hasEvery","hasSome","orderId","quantity","total","OrderStatus","userId_productId","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","push","increment","decrement","multiply","divide"]'),
  graph: "pwM8YAwDAADgAQAgBwAA4QEAIHQAAOIBADB1AAAMABB2AADiAQAwdwEAAAABeAEAvwEAIXkBAL8BACF6QADFAQAhlQFAAMUBACGqAQIA1gEAIa0BAADnAQAgAQAAAAEAIAsDAADgAQAgCgAA1wEAIHQAAOUBADB1AAADABB2AADlAQAwdwEAvwEAIXgBAL8BACF6QADFAQAhjgEAAOYBrQEilQFAAMUBACGrAQgA1AEAIQIDAAD7AgAgCgAA6QIAIAsDAADgAQAgCgAA1wEAIHQAAOUBADB1AAADABB2AADlAQAwdwEAAAABeAEAvwEAIXpAAMUBACGOAQAA5gGtASKVAUAAxQEAIasBCADUAQAhAwAAAAMAIAEAAAQAMAIAAAUAIA0EAADkAQAgBwAA4QEAIHQAAOMBADB1AAAHABB2AADjAQAwdwEAvwEAIXkBAL8BACF6QADFAQAhhgEBAL8BACGVAUAAxQEAIZsBCADUAQAhqQEBAL8BACGqAQIA1gEAIQIEAAD9AgAgBwAA_AIAIA0EAADkAQAgBwAA4QEAIHQAAOMBADB1AAAHABB2AADjAQAwdwEAAAABeQEAvwEAIXpAAMUBACGGAQEAvwEAIZUBQADFAQAhmwEIANQBACGpAQEAvwEAIaoBAgDWAQAhAwAAAAcAIAEAAAgAMAIAAAkAIAMAAAAHACABAAAIADACAAAJACALAwAA4AEAIAcAAOEBACB0AADiAQAwdQAADAAQdgAA4gEAMHcBAL8BACF4AQC_AQAheQEAvwEAIXpAAMUBACGVAUAAxQEAIaoBAgDWAQAhAgMAAPsCACAHAAD8AgAgAwAAAAwAIAEAAA0AMAIAAAEAIAkDAADgAQAgBwAA4QEAIHQAAN8BADB1AAAPABB2AADfAQAwdwEAvwEAIXgBAL8BACF5AQC_AQAhekAAxQEAIQIDAAD7AgAgBwAA_AIAIAoDAADgAQAgBwAA4QEAIHQAAN8BADB1AAAPABB2AADfAQAwdwEAAAABeAEAvwEAIXkBAL8BACF6QADFAQAhrQEAAN4BACADAAAADwAgAQAAEAAwAgAAEQAgAQAAAAcAIAEAAAAMACABAAAADwAgAQAAAAcAIAMAAAAMACABAAANADACAAABACADAAAADwAgAQAAEAAwAgAAEQAgAQAAAAMAIAEAAAAMACABAAAADwAgAQAAAAEAIAMAAAAMACABAAANADACAAABACADAAAADAAgAQAADQAwAgAAAQAgAwAAAAwAIAEAAA0AMAIAAAEAIAgDAADZAgAgBwAAlwIAIHcBAAAAAXgBAAAAAXkBAAAAAXpAAAAAAZUBQAAAAAGqAQIAAAABAREAACAAIAZ3AQAAAAF4AQAAAAF5AQAAAAF6QAAAAAGVAUAAAAABqgECAAAAAQERAAAiADABEQAAIgAwCAMAANcCACAHAACVAgAgdwEA6wEAIXgBAOsBACF5AQDrAQAhekAA7AEAIZUBQADsAQAhqgECAJMCACECAAAAAQAgEQAAJQAgBncBAOsBACF4AQDrAQAheQEA6wEAIXpAAOwBACGVAUAA7AEAIaoBAgCTAgAhAgAAAAwAIBEAACcAIAIAAAAMACARAAAnACADAAAAAQAgGAAAIAAgGQAAJQAgAQAAAAEAIAEAAAAMACAFCQAA9gIAIB4AAPcCACAfAAD6AgAgIAAA-QIAICEAAPgCACAJdAAA3QEAMHUAAC4AEHYAAN0BADB3AQCmAQAheAEApgEAIXkBAKYBACF6QACnAQAhlQFAAKcBACGqAQIAzAEAIQMAAAAMACABAAAtADAdAAAuACADAAAADAAgAQAADQAwAgAAAQAgAQAAAAUAIAEAAAAFACADAAAAAwAgAQAABAAwAgAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAMAAAADACABAAAEADACAAAFACAIAwAA9QIAIAoAALUCACB3AQAAAAF4AQAAAAF6QAAAAAGOAQAAAK0BApUBQAAAAAGrAQgAAAABAREAADYAIAZ3AQAAAAF4AQAAAAF6QAAAAAGOAQAAAK0BApUBQAAAAAGrAQgAAAABAREAADgAMAERAAA4ADAIAwAA9AIAIAoAAKUCACB3AQDrAQAheAEA6wEAIXpAAOwBACGOAQAAowKtASKVAUAA7AEAIasBCACiAgAhAgAAAAUAIBEAADsAIAZ3AQDrAQAheAEA6wEAIXpAAOwBACGOAQAAowKtASKVAUAA7AEAIasBCACiAgAhAgAAAAMAIBEAAD0AIAIAAAADACARAAA9ACADAAAABQAgGAAANgAgGQAAOwAgAQAAAAUAIAEAAAADACAFCQAA7wIAIB4AAPACACAfAADzAgAgIAAA8gIAICEAAPECACAJdAAA2QEAMHUAAEQAEHYAANkBADB3AQCmAQAheAEApgEAIXpAAKcBACGOAQAA2gGtASKVAUAApwEAIasBCADKAQAhAwAAAAMAIAEAAEMAMB0AAEQAIAMAAAADACABAAAEADACAAAFACABAAAACQAgAQAAAAkAIAMAAAAHACABAAAIADACAAAJACADAAAABwAgAQAACAAwAgAACQAgAwAAAAcAIAEAAAgAMAIAAAkAIAoEAADkAgAgBwAAswIAIHcBAAAAAXkBAAAAAXpAAAAAAYYBAQAAAAGVAUAAAAABmwEIAAAAAakBAQAAAAGqAQIAAAABAREAAEwAIAh3AQAAAAF5AQAAAAF6QAAAAAGGAQEAAAABlQFAAAAAAZsBCAAAAAGpAQEAAAABqgECAAAAAQERAABOADABEQAATgAwCgQAAOICACAHAACxAgAgdwEA6wEAIXkBAOsBACF6QADsAQAhhgEBAOsBACGVAUAA7AEAIZsBCACiAgAhqQEBAOsBACGqAQIAkwIAIQIAAAAJACARAABRACAIdwEA6wEAIXkBAOsBACF6QADsAQAhhgEBAOsBACGVAUAA7AEAIZsBCACiAgAhqQEBAOsBACGqAQIAkwIAIQIAAAAHACARAABTACACAAAABwAgEQAAUwAgAwAAAAkAIBgAAEwAIBkAAFEAIAEAAAAJACABAAAABwAgBQkAAOoCACAeAADrAgAgHwAA7gIAICAAAO0CACAhAADsAgAgC3QAANgBADB1AABaABB2AADYAQAwdwEApgEAIXkBAKYBACF6QACnAQAhhgEBAKYBACGVAUAApwEAIZsBCADKAQAhqQEBAKYBACGqAQIAzAEAIQMAAAAHACABAABZADAdAABaACADAAAABwAgAQAACAAwAgAACQAgFwUAANcBACAGAADHAQAgCAAAyAEAIHQAANMBADB1AABgABB2AADTAQAwdwEAAAABekAAxQEAIYYBAQC_AQAhlQFAAMUBACGZAQEAAAABmgEBAMABACGbAQgA1AEAIZwBCADVAQAhnQECANYBACGeAQEAvwEAIZ8BAADNAQAgoAEBAMABACGhAQEAwAEAIaIBCADUAQAhowECANYBACGkASAAxAEAIaUBIADEAQAhAQAAAF0AIAEAAABdACAXBQAA1wEAIAYAAMcBACAIAADIAQAgdAAA0wEAMHUAAGAAEHYAANMBADB3AQC_AQAhekAAxQEAIYYBAQC_AQAhlQFAAMUBACGZAQEAvwEAIZoBAQDAAQAhmwEIANQBACGcAQgA1QEAIZ0BAgDWAQAhngEBAL8BACGfAQAAzQEAIKABAQDAAQAhoQEBAMABACGiAQgA1AEAIaMBAgDWAQAhpAEgAMQBACGlASAAxAEAIQcFAADpAgAgBgAAugIAIAgAALsCACCaAQAA8QEAIJwBAADxAQAgoAEAAPEBACChAQAA8QEAIAMAAABgACABAABhADACAABdACADAAAAYAAgAQAAYQAwAgAAXQAgAwAAAGAAIAEAAGEAMAIAAF0AIBQFAADmAgAgBgAA5wIAIAgAAOgCACB3AQAAAAF6QAAAAAGGAQEAAAABlQFAAAAAAZkBAQAAAAGaAQEAAAABmwEIAAAAAZwBCAAAAAGdAQIAAAABngEBAAAAAZ8BAADlAgAgoAEBAAAAAaEBAQAAAAGiAQgAAAABowECAAAAAaQBIAAAAAGlASAAAAABAREAAGUAIBF3AQAAAAF6QAAAAAGGAQEAAAABlQFAAAAAAZkBAQAAAAGaAQEAAAABmwEIAAAAAZwBCAAAAAGdAQIAAAABngEBAAAAAZ8BAADlAgAgoAEBAAAAAaEBAQAAAAGiAQgAAAABowECAAAAAaQBIAAAAAGlASAAAAABAREAAGcAMAERAABnADAUBQAAwwIAIAYAAMQCACAIAADFAgAgdwEA6wEAIXpAAOwBACGGAQEA6wEAIZUBQADsAQAhmQEBAOsBACGaAQEA9QEAIZsBCACiAgAhnAEIAMECACGdAQIAkwIAIZ4BAQDrAQAhnwEAAMICACCgAQEA9QEAIaEBAQD1AQAhogEIAKICACGjAQIAkwIAIaQBIAD5AQAhpQEgAPkBACECAAAAXQAgEQAAagAgEXcBAOsBACF6QADsAQAhhgEBAOsBACGVAUAA7AEAIZkBAQDrAQAhmgEBAPUBACGbAQgAogIAIZwBCADBAgAhnQECAJMCACGeAQEA6wEAIZ8BAADCAgAgoAEBAPUBACGhAQEA9QEAIaIBCACiAgAhowECAJMCACGkASAA-QEAIaUBIAD5AQAhAgAAAGAAIBEAAGwAIAIAAABgACARAABsACADAAAAXQAgGAAAZQAgGQAAagAgAQAAAF0AIAEAAABgACAJCQAAvAIAIB4AAL0CACAfAADAAgAgIAAAvwIAICEAAL4CACCaAQAA8QEAIJwBAADxAQAgoAEAAPEBACChAQAA8QEAIBR0AADJAQAwdQAAcwAQdgAAyQEAMHcBAKYBACF6QACnAQAhhgEBAKYBACGVAUAApwEAIZkBAQCmAQAhmgEBAK4BACGbAQgAygEAIZwBCADLAQAhnQECAMwBACGeAQEApgEAIZ8BAADNAQAgoAEBAK4BACGhAQEArgEAIaIBCADKAQAhowECAMwBACGkASAAsgEAIaUBIACyAQAhAwAAAGAAIAEAAHIAMB0AAHMAIAMAAABgACABAABhADACAABdACAWBgAAxwEAIAgAAMgBACALAADGAQAgdAAAvgEAMHUAAHkAEHYAAL4BADB3AQAAAAF6QADFAQAhhgEBAL8BACGHAQEAAAABiAEBAL8BACGJAQEAAAABigEBAMABACGMAQAAwQGMASKOAQAAwgGOASKPAQEAwAEAIZABAQDAAQAhkQEBAMABACGSAUAAwwEAIZMBIADEAQAhlAEBAMABACGVAUAAxQEAIQEAAAB2ACABAAAAdgAgFgYAAMcBACAIAADIAQAgCwAAxgEAIHQAAL4BADB1AAB5ABB2AAC-AQAwdwEAvwEAIXpAAMUBACGGAQEAvwEAIYcBAQC_AQAhiAEBAL8BACGJAQEAwAEAIYoBAQDAAQAhjAEAAMEBjAEijgEAAMIBjgEijwEBAMABACGQAQEAwAEAIZEBAQDAAQAhkgFAAMMBACGTASAAxAEAIZQBAQDAAQAhlQFAAMUBACEKBgAAugIAIAgAALsCACALAAC5AgAgiQEAAPEBACCKAQAA8QEAII8BAADxAQAgkAEAAPEBACCRAQAA8QEAIJIBAADxAQAglAEAAPEBACADAAAAeQAgAQAAegAwAgAAdgAgAwAAAHkAIAEAAHoAMAIAAHYAIAMAAAB5ACABAAB6ADACAAB2ACATBgAAtwIAIAgAALgCACALAAC2AgAgdwEAAAABekAAAAABhgEBAAAAAYcBAQAAAAGIAQEAAAABiQEBAAAAAYoBAQAAAAGMAQAAAIwBAo4BAAAAjgECjwEBAAAAAZABAQAAAAGRAQEAAAABkgFAAAAAAZMBIAAAAAGUAQEAAAABlQFAAAAAAQERAAB-ACAQdwEAAAABekAAAAABhgEBAAAAAYcBAQAAAAGIAQEAAAABiQEBAAAAAYoBAQAAAAGMAQAAAIwBAo4BAAAAjgECjwEBAAAAAZABAQAAAAGRAQEAAAABkgFAAAAAAZMBIAAAAAGUAQEAAAABlQFAAAAAAQERAACAAQAwAREAAIABADATBgAA-wEAIAgAAPwBACALAAD6AQAgdwEA6wEAIXpAAOwBACGGAQEA6wEAIYcBAQDrAQAhiAEBAOsBACGJAQEA9QEAIYoBAQD1AQAhjAEAAPYBjAEijgEAAPcBjgEijwEBAPUBACGQAQEA9QEAIZEBAQD1AQAhkgFAAPgBACGTASAA-QEAIZQBAQD1AQAhlQFAAOwBACECAAAAdgAgEQAAgwEAIBB3AQDrAQAhekAA7AEAIYYBAQDrAQAhhwEBAOsBACGIAQEA6wEAIYkBAQD1AQAhigEBAPUBACGMAQAA9gGMASKOAQAA9wGOASKPAQEA9QEAIZABAQD1AQAhkQEBAPUBACGSAUAA-AEAIZMBIAD5AQAhlAEBAPUBACGVAUAA7AEAIQIAAAB5ACARAACFAQAgAgAAAHkAIBEAAIUBACADAAAAdgAgGAAAfgAgGQAAgwEAIAEAAAB2ACABAAAAeQAgCgkAAPIBACAgAAD0AQAgIQAA8wEAIIkBAADxAQAgigEAAPEBACCPAQAA8QEAIJABAADxAQAgkQEAAPEBACCSAQAA8QEAIJQBAADxAQAgE3QAAK0BADB1AACMAQAQdgAArQEAMHcBAKYBACF6QACnAQAhhgEBAKYBACGHAQEApgEAIYgBAQCmAQAhiQEBAK4BACGKAQEArgEAIYwBAACvAYwBIo4BAACwAY4BIo8BAQCuAQAhkAEBAK4BACGRAQEArgEAIZIBQACxAQAhkwEgALIBACGUAQEArgEAIZUBQACnAQAhAwAAAHkAIAEAAIsBADAdAACMAQAgAwAAAHkAIAEAAHoAMAIAAHYAIAEAAAARACABAAAAEQAgAwAAAA8AIAEAABAAMAIAABEAIAMAAAAPACABAAAQADACAAARACADAAAADwAgAQAAEAAwAgAAEQAgBgMAAO8BACAHAADwAQAgdwEAAAABeAEAAAABeQEAAAABekAAAAABAREAAJQBACAEdwEAAAABeAEAAAABeQEAAAABekAAAAABAREAAJYBADABEQAAlgEAMAYDAADtAQAgBwAA7gEAIHcBAOsBACF4AQDrAQAheQEA6wEAIXpAAOwBACECAAAAEQAgEQAAmQEAIAR3AQDrAQAheAEA6wEAIXkBAOsBACF6QADsAQAhAgAAAA8AIBEAAJsBACACAAAADwAgEQAAmwEAIAMAAAARACAYAACUAQAgGQAAmQEAIAEAAAARACABAAAADwAgAwkAAOgBACAgAADqAQAgIQAA6QEAIAd0AAClAQAwdQAAogEAEHYAAKUBADB3AQCmAQAheAEApgEAIXkBAKYBACF6QACnAQAhAwAAAA8AIAEAAKEBADAdAACiAQAgAwAAAA8AIAEAABAAMAIAABEAIAd0AAClAQAwdQAAogEAEHYAAKUBADB3AQCmAQAheAEApgEAIXkBAKYBACF6QACnAQAhDgkAAKkBACAgAACsAQAgIQAArAEAIHsBAAAAAXwBAAAABH0BAAAABH4BAAAAAX8BAAAAAYABAQAAAAGBAQEAAAABggEBAKsBACGDAQEAAAABhAEBAAAAAYUBAQAAAAELCQAAqQEAICAAAKoBACAhAACqAQAge0AAAAABfEAAAAAEfUAAAAAEfkAAAAABf0AAAAABgAFAAAAAAYEBQAAAAAGCAUAAqAEAIQsJAACpAQAgIAAAqgEAICEAAKoBACB7QAAAAAF8QAAAAAR9QAAAAAR-QAAAAAF_QAAAAAGAAUAAAAABgQFAAAAAAYIBQACoAQAhCHsCAAAAAXwCAAAABH0CAAAABH4CAAAAAX8CAAAAAYABAgAAAAGBAQIAAAABggECAKkBACEIe0AAAAABfEAAAAAEfUAAAAAEfkAAAAABf0AAAAABgAFAAAAAAYEBQAAAAAGCAUAAqgEAIQ4JAACpAQAgIAAArAEAICEAAKwBACB7AQAAAAF8AQAAAAR9AQAAAAR-AQAAAAF_AQAAAAGAAQEAAAABgQEBAAAAAYIBAQCrAQAhgwEBAAAAAYQBAQAAAAGFAQEAAAABC3sBAAAAAXwBAAAABH0BAAAABH4BAAAAAX8BAAAAAYABAQAAAAGBAQEAAAABggEBAKwBACGDAQEAAAABhAEBAAAAAYUBAQAAAAETdAAArQEAMHUAAIwBABB2AACtAQAwdwEApgEAIXpAAKcBACGGAQEApgEAIYcBAQCmAQAhiAEBAKYBACGJAQEArgEAIYoBAQCuAQAhjAEAAK8BjAEijgEAALABjgEijwEBAK4BACGQAQEArgEAIZEBAQCuAQAhkgFAALEBACGTASAAsgEAIZQBAQCuAQAhlQFAAKcBACEOCQAAtgEAICAAAL0BACAhAAC9AQAgewEAAAABfAEAAAAFfQEAAAAFfgEAAAABfwEAAAABgAEBAAAAAYEBAQAAAAGCAQEAvAEAIYMBAQAAAAGEAQEAAAABhQEBAAAAAQcJAACpAQAgIAAAuwEAICEAALsBACB7AAAAjAECfAAAAIwBCH0AAACMAQiCAQAAugGMASIHCQAAqQEAICAAALkBACAhAAC5AQAgewAAAI4BAnwAAACOAQh9AAAAjgEIggEAALgBjgEiCwkAALYBACAgAAC3AQAgIQAAtwEAIHtAAAAAAXxAAAAABX1AAAAABX5AAAAAAX9AAAAAAYABQAAAAAGBAUAAAAABggFAALUBACEFCQAAqQEAICAAALQBACAhAAC0AQAgeyAAAAABggEgALMBACEFCQAAqQEAICAAALQBACAhAAC0AQAgeyAAAAABggEgALMBACECeyAAAAABggEgALQBACELCQAAtgEAICAAALcBACAhAAC3AQAge0AAAAABfEAAAAAFfUAAAAAFfkAAAAABf0AAAAABgAFAAAAAAYEBQAAAAAGCAUAAtQEAIQh7AgAAAAF8AgAAAAV9AgAAAAV-AgAAAAF_AgAAAAGAAQIAAAABgQECAAAAAYIBAgC2AQAhCHtAAAAAAXxAAAAABX1AAAAABX5AAAAAAX9AAAAAAYABQAAAAAGBAUAAAAABggFAALcBACEHCQAAqQEAICAAALkBACAhAAC5AQAgewAAAI4BAnwAAACOAQh9AAAAjgEIggEAALgBjgEiBHsAAACOAQJ8AAAAjgEIfQAAAI4BCIIBAAC5AY4BIgcJAACpAQAgIAAAuwEAICEAALsBACB7AAAAjAECfAAAAIwBCH0AAACMAQiCAQAAugGMASIEewAAAIwBAnwAAACMAQh9AAAAjAEIggEAALsBjAEiDgkAALYBACAgAAC9AQAgIQAAvQEAIHsBAAAAAXwBAAAABX0BAAAABX4BAAAAAX8BAAAAAYABAQAAAAGBAQEAAAABggEBALwBACGDAQEAAAABhAEBAAAAAYUBAQAAAAELewEAAAABfAEAAAAFfQEAAAAFfgEAAAABfwEAAAABgAEBAAAAAYEBAQAAAAGCAQEAvQEAIYMBAQAAAAGEAQEAAAABhQEBAAAAARYGAADHAQAgCAAAyAEAIAsAAMYBACB0AAC-AQAwdQAAeQAQdgAAvgEAMHcBAL8BACF6QADFAQAhhgEBAL8BACGHAQEAvwEAIYgBAQC_AQAhiQEBAMABACGKAQEAwAEAIYwBAADBAYwBIo4BAADCAY4BIo8BAQDAAQAhkAEBAMABACGRAQEAwAEAIZIBQADDAQAhkwEgAMQBACGUAQEAwAEAIZUBQADFAQAhC3sBAAAAAXwBAAAABH0BAAAABH4BAAAAAX8BAAAAAYABAQAAAAGBAQEAAAABggEBAKwBACGDAQEAAAABhAEBAAAAAYUBAQAAAAELewEAAAABfAEAAAAFfQEAAAAFfgEAAAABfwEAAAABgAEBAAAAAYEBAQAAAAGCAQEAvQEAIYMBAQAAAAGEAQEAAAABhQEBAAAAAQR7AAAAjAECfAAAAIwBCH0AAACMAQiCAQAAuwGMASIEewAAAI4BAnwAAACOAQh9AAAAjgEIggEAALkBjgEiCHtAAAAAAXxAAAAABX1AAAAABX5AAAAAAX9AAAAAAYABQAAAAAGBAUAAAAABggFAALcBACECeyAAAAABggEgALQBACEIe0AAAAABfEAAAAAEfUAAAAAEfkAAAAABf0AAAAABgAFAAAAAAYEBQAAAAAGCAUAAqgEAIQOWAQAAAwAglwEAAAMAIJgBAAADACADlgEAAAwAIJcBAAAMACCYAQAADAAgA5YBAAAPACCXAQAADwAgmAEAAA8AIBR0AADJAQAwdQAAcwAQdgAAyQEAMHcBAKYBACF6QACnAQAhhgEBAKYBACGVAUAApwEAIZkBAQCmAQAhmgEBAK4BACGbAQgAygEAIZwBCADLAQAhnQECAMwBACGeAQEApgEAIZ8BAADNAQAgoAEBAK4BACGhAQEArgEAIaIBCADKAQAhowECAMwBACGkASAAsgEAIaUBIACyAQAhDQkAAKkBACAeAADPAQAgHwAAzwEAICAAAM8BACAhAADPAQAgewgAAAABfAgAAAAEfQgAAAAEfggAAAABfwgAAAABgAEIAAAAAYEBCAAAAAGCAQgA0gEAIQ0JAAC2AQAgHgAA0QEAIB8AANEBACAgAADRAQAgIQAA0QEAIHsIAAAAAXwIAAAABX0IAAAABX4IAAAAAX8IAAAAAYABCAAAAAGBAQgAAAABggEIANABACENCQAAqQEAIB4AAM8BACAfAACpAQAgIAAAqQEAICEAAKkBACB7AgAAAAF8AgAAAAR9AgAAAAR-AgAAAAF_AgAAAAGAAQIAAAABgQECAAAAAYIBAgDOAQAhBHsBAAAABaYBAQAAAAGnAQEAAAAEqAEBAAAABA0JAACpAQAgHgAAzwEAIB8AAKkBACAgAACpAQAgIQAAqQEAIHsCAAAAAXwCAAAABH0CAAAABH4CAAAAAX8CAAAAAYABAgAAAAGBAQIAAAABggECAM4BACEIewgAAAABfAgAAAAEfQgAAAAEfggAAAABfwgAAAABgAEIAAAAAYEBCAAAAAGCAQgAzwEAIQ0JAAC2AQAgHgAA0QEAIB8AANEBACAgAADRAQAgIQAA0QEAIHsIAAAAAXwIAAAABX0IAAAABX4IAAAAAX8IAAAAAYABCAAAAAGBAQgAAAABggEIANABACEIewgAAAABfAgAAAAFfQgAAAAFfggAAAABfwgAAAABgAEIAAAAAYEBCAAAAAGCAQgA0QEAIQ0JAACpAQAgHgAAzwEAIB8AAM8BACAgAADPAQAgIQAAzwEAIHsIAAAAAXwIAAAABH0IAAAABH4IAAAAAX8IAAAAAYABCAAAAAGBAQgAAAABggEIANIBACEXBQAA1wEAIAYAAMcBACAIAADIAQAgdAAA0wEAMHUAAGAAEHYAANMBADB3AQC_AQAhekAAxQEAIYYBAQC_AQAhlQFAAMUBACGZAQEAvwEAIZoBAQDAAQAhmwEIANQBACGcAQgA1QEAIZ0BAgDWAQAhngEBAL8BACGfAQAAzQEAIKABAQDAAQAhoQEBAMABACGiAQgA1AEAIaMBAgDWAQAhpAEgAMQBACGlASAAxAEAIQh7CAAAAAF8CAAAAAR9CAAAAAR-CAAAAAF_CAAAAAGAAQgAAAABgQEIAAAAAYIBCADPAQAhCHsIAAAAAXwIAAAABX0IAAAABX4IAAAAAX8IAAAAAYABCAAAAAGBAQgAAAABggEIANEBACEIewIAAAABfAIAAAAEfQIAAAAEfgIAAAABfwIAAAABgAECAAAAAYEBAgAAAAGCAQIAqQEAIQOWAQAABwAglwEAAAcAIJgBAAAHACALdAAA2AEAMHUAAFoAEHYAANgBADB3AQCmAQAheQEApgEAIXpAAKcBACGGAQEApgEAIZUBQACnAQAhmwEIAMoBACGpAQEApgEAIaoBAgDMAQAhCXQAANkBADB1AABEABB2AADZAQAwdwEApgEAIXgBAKYBACF6QACnAQAhjgEAANoBrQEilQFAAKcBACGrAQgAygEAIQcJAACpAQAgIAAA3AEAICEAANwBACB7AAAArQECfAAAAK0BCH0AAACtAQiCAQAA2wGtASIHCQAAqQEAICAAANwBACAhAADcAQAgewAAAK0BAnwAAACtAQh9AAAArQEIggEAANsBrQEiBHsAAACtAQJ8AAAArQEIfQAAAK0BCIIBAADcAa0BIgl0AADdAQAwdQAALgAQdgAA3QEAMHcBAKYBACF4AQCmAQAheQEApgEAIXpAAKcBACGVAUAApwEAIaoBAgDMAQAhAngBAAAAAXkBAAAAAQkDAADgAQAgBwAA4QEAIHQAAN8BADB1AAAPABB2AADfAQAwdwEAvwEAIXgBAL8BACF5AQC_AQAhekAAxQEAIRgGAADHAQAgCAAAyAEAIAsAAMYBACB0AAC-AQAwdQAAeQAQdgAAvgEAMHcBAL8BACF6QADFAQAhhgEBAL8BACGHAQEAvwEAIYgBAQC_AQAhiQEBAMABACGKAQEAwAEAIYwBAADBAYwBIo4BAADCAY4BIo8BAQDAAQAhkAEBAMABACGRAQEAwAEAIZIBQADDAQAhkwEgAMQBACGUAQEAwAEAIZUBQADFAQAhrgEAAHkAIK8BAAB5ACAZBQAA1wEAIAYAAMcBACAIAADIAQAgdAAA0wEAMHUAAGAAEHYAANMBADB3AQC_AQAhekAAxQEAIYYBAQC_AQAhlQFAAMUBACGZAQEAvwEAIZoBAQDAAQAhmwEIANQBACGcAQgA1QEAIZ0BAgDWAQAhngEBAL8BACGfAQAAzQEAIKABAQDAAQAhoQEBAMABACGiAQgA1AEAIaMBAgDWAQAhpAEgAMQBACGlASAAxAEAIa4BAABgACCvAQAAYAAgCwMAAOABACAHAADhAQAgdAAA4gEAMHUAAAwAEHYAAOIBADB3AQC_AQAheAEAvwEAIXkBAL8BACF6QADFAQAhlQFAAMUBACGqAQIA1gEAIQ0EAADkAQAgBwAA4QEAIHQAAOMBADB1AAAHABB2AADjAQAwdwEAvwEAIXkBAL8BACF6QADFAQAhhgEBAL8BACGVAUAAxQEAIZsBCADUAQAhqQEBAL8BACGqAQIA1gEAIQ0DAADgAQAgCgAA1wEAIHQAAOUBADB1AAADABB2AADlAQAwdwEAvwEAIXgBAL8BACF6QADFAQAhjgEAAOYBrQEilQFAAMUBACGrAQgA1AEAIa4BAAADACCvAQAAAwAgCwMAAOABACAKAADXAQAgdAAA5QEAMHUAAAMAEHYAAOUBADB3AQC_AQAheAEAvwEAIXpAAMUBACGOAQAA5gGtASKVAUAAxQEAIasBCADUAQAhBHsAAACtAQJ8AAAArQEIfQAAAK0BCIIBAADcAa0BIgJ4AQAAAAF5AQAAAAEAAAABswEBAAAAAQGzAUAAAAABBRgAAKADACAZAACmAwAgsAEAAKEDACCxAQAApQMAILYBAAB2ACAFGAAAngMAIBkAAKMDACCwAQAAnwMAILEBAACiAwAgtgEAAF0AIAMYAACgAwAgsAEAAKEDACC2AQAAdgAgAxgAAJ4DACCwAQAAnwMAILYBAABdACAAAAAAAbMBAQAAAAEBswEAAACMAQIBswEAAACOAQIBswFAAAAAAQGzASAAAAABCxgAAJgCADAZAACdAgAwsAEAAJkCADCxAQAAmgIAMLIBAACbAgAgswEAAJwCADC0AQAAnAIAMLUBAACcAgAwtgEAAJwCADC3AQAAngIAMLgBAACfAgAwCxgAAIkCADAZAACOAgAwsAEAAIoCADCxAQAAiwIAMLIBAACMAgAgswEAAI0CADC0AQAAjQIAMLUBAACNAgAwtgEAAI0CADC3AQAAjwIAMLgBAACQAgAwCxgAAP0BADAZAACCAgAwsAEAAP4BADCxAQAA_wEAMLIBAACAAgAgswEAAIECADC0AQAAgQIAMLUBAACBAgAwtgEAAIECADC3AQAAgwIAMLgBAACEAgAwBAcAAPABACB3AQAAAAF5AQAAAAF6QAAAAAECAAAAEQAgGAAAiAIAIAMAAAARACAYAACIAgAgGQAAhwIAIAERAACdAwAwCgMAAOABACAHAADhAQAgdAAA3wEAMHUAAA8AEHYAAN8BADB3AQAAAAF4AQC_AQAheQEAvwEAIXpAAMUBACGtAQAA3gEAIAIAAAARACARAACHAgAgAgAAAIUCACARAACGAgAgB3QAAIQCADB1AACFAgAQdgAAhAIAMHcBAL8BACF4AQC_AQAheQEAvwEAIXpAAMUBACEHdAAAhAIAMHUAAIUCABB2AACEAgAwdwEAvwEAIXgBAL8BACF5AQC_AQAhekAAxQEAIQN3AQDrAQAheQEA6wEAIXpAAOwBACEEBwAA7gEAIHcBAOsBACF5AQDrAQAhekAA7AEAIQQHAADwAQAgdwEAAAABeQEAAAABekAAAAABBgcAAJcCACB3AQAAAAF5AQAAAAF6QAAAAAGVAUAAAAABqgECAAAAAQIAAAABACAYAACWAgAgAwAAAAEAIBgAAJYCACAZAACUAgAgAREAAJwDADAMAwAA4AEAIAcAAOEBACB0AADiAQAwdQAADAAQdgAA4gEAMHcBAAAAAXgBAL8BACF5AQC_AQAhekAAxQEAIZUBQADFAQAhqgECANYBACGtAQAA5wEAIAIAAAABACARAACUAgAgAgAAAJECACARAACSAgAgCXQAAJACADB1AACRAgAQdgAAkAIAMHcBAL8BACF4AQC_AQAheQEAvwEAIXpAAMUBACGVAUAAxQEAIaoBAgDWAQAhCXQAAJACADB1AACRAgAQdgAAkAIAMHcBAL8BACF4AQC_AQAheQEAvwEAIXpAAMUBACGVAUAAxQEAIaoBAgDWAQAhBXcBAOsBACF5AQDrAQAhekAA7AEAIZUBQADsAQAhqgECAJMCACEFswECAAAAAboBAgAAAAG7AQIAAAABvAECAAAAAb0BAgAAAAEGBwAAlQIAIHcBAOsBACF5AQDrAQAhekAA7AEAIZUBQADsAQAhqgECAJMCACEFGAAAlwMAIBkAAJoDACCwAQAAmAMAILEBAACZAwAgtgEAAF0AIAYHAACXAgAgdwEAAAABeQEAAAABekAAAAABlQFAAAAAAaoBAgAAAAEDGAAAlwMAILABAACYAwAgtgEAAF0AIAYKAAC1AgAgdwEAAAABekAAAAABjgEAAACtAQKVAUAAAAABqwEIAAAAAQIAAAAFACAYAAC0AgAgAwAAAAUAIBgAALQCACAZAACkAgAgAREAAJYDADALAwAA4AEAIAoAANcBACB0AADlAQAwdQAAAwAQdgAA5QEAMHcBAAAAAXgBAL8BACF6QADFAQAhjgEAAOYBrQEilQFAAMUBACGrAQgA1AEAIQIAAAAFACARAACkAgAgAgAAAKACACARAAChAgAgCXQAAJ8CADB1AACgAgAQdgAAnwIAMHcBAL8BACF4AQC_AQAhekAAxQEAIY4BAADmAa0BIpUBQADFAQAhqwEIANQBACEJdAAAnwIAMHUAAKACABB2AACfAgAwdwEAvwEAIXgBAL8BACF6QADFAQAhjgEAAOYBrQEilQFAAMUBACGrAQgA1AEAIQV3AQDrAQAhekAA7AEAIY4BAACjAq0BIpUBQADsAQAhqwEIAKICACEFswEIAAAAAboBCAAAAAG7AQgAAAABvAEIAAAAAb0BCAAAAAEBswEAAACtAQIGCgAApQIAIHcBAOsBACF6QADsAQAhjgEAAKMCrQEilQFAAOwBACGrAQgAogIAIQsYAACmAgAwGQAAqwIAMLABAACnAgAwsQEAAKgCADCyAQAAqQIAILMBAACqAgAwtAEAAKoCADC1AQAAqgIAMLYBAACqAgAwtwEAAKwCADC4AQAArQIAMAgHAACzAgAgdwEAAAABeQEAAAABekAAAAABhgEBAAAAAZUBQAAAAAGbAQgAAAABqgECAAAAAQIAAAAJACAYAACyAgAgAwAAAAkAIBgAALICACAZAACwAgAgAREAAJUDADANBAAA5AEAIAcAAOEBACB0AADjAQAwdQAABwAQdgAA4wEAMHcBAAAAAXkBAL8BACF6QADFAQAhhgEBAL8BACGVAUAAxQEAIZsBCADUAQAhqQEBAL8BACGqAQIA1gEAIQIAAAAJACARAACwAgAgAgAAAK4CACARAACvAgAgC3QAAK0CADB1AACuAgAQdgAArQIAMHcBAL8BACF5AQC_AQAhekAAxQEAIYYBAQC_AQAhlQFAAMUBACGbAQgA1AEAIakBAQC_AQAhqgECANYBACELdAAArQIAMHUAAK4CABB2AACtAgAwdwEAvwEAIXkBAL8BACF6QADFAQAhhgEBAL8BACGVAUAAxQEAIZsBCADUAQAhqQEBAL8BACGqAQIA1gEAIQd3AQDrAQAheQEA6wEAIXpAAOwBACGGAQEA6wEAIZUBQADsAQAhmwEIAKICACGqAQIAkwIAIQgHAACxAgAgdwEA6wEAIXkBAOsBACF6QADsAQAhhgEBAOsBACGVAUAA7AEAIZsBCACiAgAhqgECAJMCACEFGAAAkAMAIBkAAJMDACCwAQAAkQMAILEBAACSAwAgtgEAAF0AIAgHAACzAgAgdwEAAAABeQEAAAABekAAAAABhgEBAAAAAZUBQAAAAAGbAQgAAAABqgECAAAAAQMYAACQAwAgsAEAAJEDACC2AQAAXQAgBgoAALUCACB3AQAAAAF6QAAAAAGOAQAAAK0BApUBQAAAAAGrAQgAAAABBBgAAKYCADCwAQAApwIAMLIBAACpAgAgtgEAAKoCADAEGAAAmAIAMLABAACZAgAwsgEAAJsCACC2AQAAnAIAMAQYAACJAgAwsAEAAIoCADCyAQAAjAIAILYBAACNAgAwBBgAAP0BADCwAQAA_gEAMLIBAACAAgAgtgEAAIECADAAAAAAAAAAAAWzAQgAAAABugEIAAAAAbsBCAAAAAG8AQgAAAABvQEIAAAAAQKzAQEAAAAEuQEBAAAABQsYAADaAgAwGQAA3gIAMLABAADbAgAwsQEAANwCADCyAQAA3QIAILMBAACqAgAwtAEAAKoCADC1AQAAqgIAMLYBAACqAgAwtwEAAN8CADC4AQAArQIAMAsYAADPAgAwGQAA0wIAMLABAADQAgAwsQEAANECADCyAQAA0gIAILMBAACNAgAwtAEAAI0CADC1AQAAjQIAMLYBAACNAgAwtwEAANQCADC4AQAAkAIAMAsYAADGAgAwGQAAygIAMLABAADHAgAwsQEAAMgCADCyAQAAyQIAILMBAACBAgAwtAEAAIECADC1AQAAgQIAMLYBAACBAgAwtwEAAMsCADC4AQAAhAIAMAQDAADvAQAgdwEAAAABeAEAAAABekAAAAABAgAAABEAIBgAAM4CACADAAAAEQAgGAAAzgIAIBkAAM0CACABEQAAjwMAMAIAAAARACARAADNAgAgAgAAAIUCACARAADMAgAgA3cBAOsBACF4AQDrAQAhekAA7AEAIQQDAADtAQAgdwEA6wEAIXgBAOsBACF6QADsAQAhBAMAAO8BACB3AQAAAAF4AQAAAAF6QAAAAAEGAwAA2QIAIHcBAAAAAXgBAAAAAXpAAAAAAZUBQAAAAAGqAQIAAAABAgAAAAEAIBgAANgCACADAAAAAQAgGAAA2AIAIBkAANYCACABEQAAjgMAMAIAAAABACARAADWAgAgAgAAAJECACARAADVAgAgBXcBAOsBACF4AQDrAQAhekAA7AEAIZUBQADsAQAhqgECAJMCACEGAwAA1wIAIHcBAOsBACF4AQDrAQAhekAA7AEAIZUBQADsAQAhqgECAJMCACEFGAAAiQMAIBkAAIwDACCwAQAAigMAILEBAACLAwAgtgEAAHYAIAYDAADZAgAgdwEAAAABeAEAAAABekAAAAABlQFAAAAAAaoBAgAAAAEDGAAAiQMAILABAACKAwAgtgEAAHYAIAgEAADkAgAgdwEAAAABekAAAAABhgEBAAAAAZUBQAAAAAGbAQgAAAABqQEBAAAAAaoBAgAAAAECAAAACQAgGAAA4wIAIAMAAAAJACAYAADjAgAgGQAA4QIAIAERAACIAwAwAgAAAAkAIBEAAOECACACAAAArgIAIBEAAOACACAHdwEA6wEAIXpAAOwBACGGAQEA6wEAIZUBQADsAQAhmwEIAKICACGpAQEA6wEAIaoBAgCTAgAhCAQAAOICACB3AQDrAQAhekAA7AEAIYYBAQDrAQAhlQFAAOwBACGbAQgAogIAIakBAQDrAQAhqgECAJMCACEFGAAAgwMAIBkAAIYDACCwAQAAhAMAILEBAACFAwAgtgEAAAUAIAgEAADkAgAgdwEAAAABekAAAAABhgEBAAAAAZUBQAAAAAGbAQgAAAABqQEBAAAAAaoBAgAAAAEDGAAAgwMAILABAACEAwAgtgEAAAUAIAGzAQEAAAAEBBgAANoCADCwAQAA2wIAMLIBAADdAgAgtgEAAKoCADAEGAAAzwIAMLABAADQAgAwsgEAANICACC2AQAAjQIAMAQYAADGAgAwsAEAAMcCADCyAQAAyQIAILYBAACBAgAwAAAAAAAAAAAAAAAFGAAA_gIAIBkAAIEDACCwAQAA_wIAILEBAACAAwAgtgEAAHYAIAMYAAD-AgAgsAEAAP8CACC2AQAAdgAgAAAAAAAKBgAAugIAIAgAALsCACALAAC5AgAgiQEAAPEBACCKAQAA8QEAII8BAADxAQAgkAEAAPEBACCRAQAA8QEAIJIBAADxAQAglAEAAPEBACAHBQAA6QIAIAYAALoCACAIAAC7AgAgmgEAAPEBACCcAQAA8QEAIKABAADxAQAgoQEAAPEBACACAwAA-wIAIAoAAOkCACASBgAAtwIAIAgAALgCACB3AQAAAAF6QAAAAAGGAQEAAAABhwEBAAAAAYgBAQAAAAGJAQEAAAABigEBAAAAAYwBAAAAjAECjgEAAACOAQKPAQEAAAABkAEBAAAAAZEBAQAAAAGSAUAAAAABkwEgAAAAAZQBAQAAAAGVAUAAAAABAgAAAHYAIBgAAP4CACADAAAAeQAgGAAA_gIAIBkAAIIDACAUAAAAeQAgBgAA-wEAIAgAAPwBACARAACCAwAgdwEA6wEAIXpAAOwBACGGAQEA6wEAIYcBAQDrAQAhiAEBAOsBACGJAQEA9QEAIYoBAQD1AQAhjAEAAPYBjAEijgEAAPcBjgEijwEBAPUBACGQAQEA9QEAIZEBAQD1AQAhkgFAAPgBACGTASAA-QEAIZQBAQD1AQAhlQFAAOwBACESBgAA-wEAIAgAAPwBACB3AQDrAQAhekAA7AEAIYYBAQDrAQAhhwEBAOsBACGIAQEA6wEAIYkBAQD1AQAhigEBAPUBACGMAQAA9gGMASKOAQAA9wGOASKPAQEA9QEAIZABAQD1AQAhkQEBAPUBACGSAUAA-AEAIZMBIAD5AQAhlAEBAPUBACGVAUAA7AEAIQcDAAD1AgAgdwEAAAABeAEAAAABekAAAAABjgEAAACtAQKVAUAAAAABqwEIAAAAAQIAAAAFACAYAACDAwAgAwAAAAMAIBgAAIMDACAZAACHAwAgCQAAAAMAIAMAAPQCACARAACHAwAgdwEA6wEAIXgBAOsBACF6QADsAQAhjgEAAKMCrQEilQFAAOwBACGrAQgAogIAIQcDAAD0AgAgdwEA6wEAIXgBAOsBACF6QADsAQAhjgEAAKMCrQEilQFAAOwBACGrAQgAogIAIQd3AQAAAAF6QAAAAAGGAQEAAAABlQFAAAAAAZsBCAAAAAGpAQEAAAABqgECAAAAARIIAAC4AgAgCwAAtgIAIHcBAAAAAXpAAAAAAYYBAQAAAAGHAQEAAAABiAEBAAAAAYkBAQAAAAGKAQEAAAABjAEAAACMAQKOAQAAAI4BAo8BAQAAAAGQAQEAAAABkQEBAAAAAZIBQAAAAAGTASAAAAABlAEBAAAAAZUBQAAAAAECAAAAdgAgGAAAiQMAIAMAAAB5ACAYAACJAwAgGQAAjQMAIBQAAAB5ACAIAAD8AQAgCwAA-gEAIBEAAI0DACB3AQDrAQAhekAA7AEAIYYBAQDrAQAhhwEBAOsBACGIAQEA6wEAIYkBAQD1AQAhigEBAPUBACGMAQAA9gGMASKOAQAA9wGOASKPAQEA9QEAIZABAQD1AQAhkQEBAPUBACGSAUAA-AEAIZMBIAD5AQAhlAEBAPUBACGVAUAA7AEAIRIIAAD8AQAgCwAA-gEAIHcBAOsBACF6QADsAQAhhgEBAOsBACGHAQEA6wEAIYgBAQDrAQAhiQEBAPUBACGKAQEA9QEAIYwBAAD2AYwBIo4BAAD3AY4BIo8BAQD1AQAhkAEBAPUBACGRAQEA9QEAIZIBQAD4AQAhkwEgAPkBACGUAQEA9QEAIZUBQADsAQAhBXcBAAAAAXgBAAAAAXpAAAAAAZUBQAAAAAGqAQIAAAABA3cBAAAAAXgBAAAAAXpAAAAAARMGAADnAgAgCAAA6AIAIHcBAAAAAXpAAAAAAYYBAQAAAAGVAUAAAAABmQEBAAAAAZoBAQAAAAGbAQgAAAABnAEIAAAAAZ0BAgAAAAGeAQEAAAABnwEAAOUCACCgAQEAAAABoQEBAAAAAaIBCAAAAAGjAQIAAAABpAEgAAAAAaUBIAAAAAECAAAAXQAgGAAAkAMAIAMAAABgACAYAACQAwAgGQAAlAMAIBUAAABgACAGAADEAgAgCAAAxQIAIBEAAJQDACB3AQDrAQAhekAA7AEAIYYBAQDrAQAhlQFAAOwBACGZAQEA6wEAIZoBAQD1AQAhmwEIAKICACGcAQgAwQIAIZ0BAgCTAgAhngEBAOsBACGfAQAAwgIAIKABAQD1AQAhoQEBAPUBACGiAQgAogIAIaMBAgCTAgAhpAEgAPkBACGlASAA-QEAIRMGAADEAgAgCAAAxQIAIHcBAOsBACF6QADsAQAhhgEBAOsBACGVAUAA7AEAIZkBAQDrAQAhmgEBAPUBACGbAQgAogIAIZwBCADBAgAhnQECAJMCACGeAQEA6wEAIZ8BAADCAgAgoAEBAPUBACGhAQEA9QEAIaIBCACiAgAhowECAJMCACGkASAA-QEAIaUBIAD5AQAhB3cBAAAAAXkBAAAAAXpAAAAAAYYBAQAAAAGVAUAAAAABmwEIAAAAAaoBAgAAAAEFdwEAAAABekAAAAABjgEAAACtAQKVAUAAAAABqwEIAAAAARMFAADmAgAgCAAA6AIAIHcBAAAAAXpAAAAAAYYBAQAAAAGVAUAAAAABmQEBAAAAAZoBAQAAAAGbAQgAAAABnAEIAAAAAZ0BAgAAAAGeAQEAAAABnwEAAOUCACCgAQEAAAABoQEBAAAAAaIBCAAAAAGjAQIAAAABpAEgAAAAAaUBIAAAAAECAAAAXQAgGAAAlwMAIAMAAABgACAYAACXAwAgGQAAmwMAIBUAAABgACAFAADDAgAgCAAAxQIAIBEAAJsDACB3AQDrAQAhekAA7AEAIYYBAQDrAQAhlQFAAOwBACGZAQEA6wEAIZoBAQD1AQAhmwEIAKICACGcAQgAwQIAIZ0BAgCTAgAhngEBAOsBACGfAQAAwgIAIKABAQD1AQAhoQEBAPUBACGiAQgAogIAIaMBAgCTAgAhpAEgAPkBACGlASAA-QEAIRMFAADDAgAgCAAAxQIAIHcBAOsBACF6QADsAQAhhgEBAOsBACGVAUAA7AEAIZkBAQDrAQAhmgEBAPUBACGbAQgAogIAIZwBCADBAgAhnQECAJMCACGeAQEA6wEAIZ8BAADCAgAgoAEBAPUBACGhAQEA9QEAIaIBCACiAgAhowECAJMCACGkASAA-QEAIaUBIAD5AQAhBXcBAAAAAXkBAAAAAXpAAAAAAZUBQAAAAAGqAQIAAAABA3cBAAAAAXkBAAAAAXpAAAAAARMFAADmAgAgBgAA5wIAIHcBAAAAAXpAAAAAAYYBAQAAAAGVAUAAAAABmQEBAAAAAZoBAQAAAAGbAQgAAAABnAEIAAAAAZ0BAgAAAAGeAQEAAAABnwEAAOUCACCgAQEAAAABoQEBAAAAAaIBCAAAAAGjAQIAAAABpAEgAAAAAaUBIAAAAAECAAAAXQAgGAAAngMAIBIGAAC3AgAgCwAAtgIAIHcBAAAAAXpAAAAAAYYBAQAAAAGHAQEAAAABiAEBAAAAAYkBAQAAAAGKAQEAAAABjAEAAACMAQKOAQAAAI4BAo8BAQAAAAGQAQEAAAABkQEBAAAAAZIBQAAAAAGTASAAAAABlAEBAAAAAZUBQAAAAAECAAAAdgAgGAAAoAMAIAMAAABgACAYAACeAwAgGQAApAMAIBUAAABgACAFAADDAgAgBgAAxAIAIBEAAKQDACB3AQDrAQAhekAA7AEAIYYBAQDrAQAhlQFAAOwBACGZAQEA6wEAIZoBAQD1AQAhmwEIAKICACGcAQgAwQIAIZ0BAgCTAgAhngEBAOsBACGfAQAAwgIAIKABAQD1AQAhoQEBAPUBACGiAQgAogIAIaMBAgCTAgAhpAEgAPkBACGlASAA-QEAIRMFAADDAgAgBgAAxAIAIHcBAOsBACF6QADsAQAhhgEBAOsBACGVAUAA7AEAIZkBAQDrAQAhmgEBAPUBACGbAQgAogIAIZwBCADBAgAhnQECAJMCACGeAQEA6wEAIZ8BAADCAgAgoAEBAPUBACGhAQEA9QEAIaIBCACiAgAhowECAJMCACGkASAA-QEAIaUBIAD5AQAhAwAAAHkAIBgAAKADACAZAACnAwAgFAAAAHkAIAYAAPsBACALAAD6AQAgEQAApwMAIHcBAOsBACF6QADsAQAhhgEBAOsBACGHAQEA6wEAIYgBAQDrAQAhiQEBAPUBACGKAQEA9QEAIYwBAAD2AYwBIo4BAAD3AY4BIo8BAQD1AQAhkAEBAPUBACGRAQEA9QEAIZIBQAD4AQAhkwEgAPkBACGUAQEA9QEAIZUBQADsAQAhEgYAAPsBACALAAD6AQAgdwEA6wEAIXpAAOwBACGGAQEA6wEAIYcBAQDrAQAhiAEBAOsBACGJAQEA9QEAIYoBAQD1AQAhjAEAAPYBjAEijgEAAPcBjgEijwEBAPUBACGQAQEA9QEAIZEBAQD1AQAhkgFAAPgBACGTASAA-QEAIZQBAQD1AQAhlQFAAOwBACECAwACBwAFBAYXAQgYBgkACQsGAwMDAAIJAAgKCgQCBAADBwAFBAULBAYOAQgSBgkABwIDAAIHAAUDBRMABhQACBUAAQoWAAMGGgAIGwALGQAAAgMAAgcABQIDAAIHAAUFCQAOHgAPHwAQIAARIQASAAAAAAAFCQAOHgAPHwAQIAARIQASAQMAAgEDAAIFCQAXHgAYHwAZIAAaIQAbAAAAAAAFCQAXHgAYHwAZIAAaIQAbAgQAAwcABQIEAAMHAAUFCQAgHgAhHwAiIAAjIQAkAAAAAAAFCQAgHgAhHwAiIAAjIQAkAAAFCQApHgAqHwArIAAsIQAtAAAAAAAFCQApHgAqHwArIAAsIQAtAAADCQAyIAAzIQA0AAAAAwkAMiAAMyEANAIDAAIHAAUCAwACBwAFAwkAOSAAOiEAOwAAAAMJADkgADohADsMAgENHAEOHQEPHgEQHwESIQETIwoUJAsVJgEWKAoXKQwaKgEbKwEcLAoiLw0jMBMkMQMlMgMmMwMnNAMoNQMpNwMqOQorOhQsPAMtPgouPxUvQAMwQQMxQgoyRRYzRhw0RwQ1SAQ2SQQ3SgQ4SwQ5TQQ6Two7UB08UgQ9VAo-VR4_VgRAVwRBWApCWx9DXCVEXgVFXwVGYgVHYwVIZAVJZgVKaApLaSZMawVNbQpObidPbwVQcAVRcQpSdChTdS5UdwJVeAJWewJXfAJYfQJZfwJagQEKW4IBL1yEAQJdhgEKXocBMF-IAQJgiQECYYoBCmKNATFjjgE1ZI8BBmWQAQZmkQEGZ5IBBmiTAQZplQEGapcBCmuYATZsmgEGbZwBCm6dATdvngEGcJ8BBnGgAQpyowE4c6QBPA"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// src/generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// src/generated/prisma/enums.ts
var Role = {
  CUSTOMER: "CUSTOMER",
  ADMIN: "ADMIN",
  SELLER: "SELLER"
};

// src/generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/app/lib/prisma.ts
var connectionString = envVars.DATABASE_URL;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/app/modules/user/user.service.ts
import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";
var registerUser = async (payload) => {
  const { photoUrl, ...rest } = payload;
  const hashedPassword = await bcrypt.hash(payload.password, 10);
  const user = await prisma.user.create({
    data: {
      ...rest,
      password: hashedPassword,
      avatar: photoUrl
      //  photoUrl → avatar mapping
    },
    select: {
      id: true,
      name: true,
      email: true,
      phone: true,
      avatar: true,
      //  correct field
      role: true,
      status: true,
      address: true,
      city: true,
      country: true,
      lastLogin: true,
      emailVerified: true,
      provider: true,
      createdAt: true,
      updatedAt: true
    }
  });
  return user;
};
var loginUser = async (payload) => {
  const { email, password } = payload;
  const user = await prisma.user.findUnique({
    where: { email }
  });
  if (!user) {
    throw new Error("User not found");
  }
  const isPasswordMatched = await bcrypt.compare(password, user.password);
  if (!isPasswordMatched) {
    throw new Error("Invalid password");
  }
  const token = jwt.sign(
    {
      id: user.id,
      email: user.email,
      role: user.role,
      name: user.name,
      phone: user.phone,
      photoUrl: user.avatar,
      status: user.status
    },
    envVars.JWT_SECRET,
    {
      expiresIn: "7d"
    }
  );
  const { password: _, ...userWithoutPassword } = user;
  return {
    accessToken: token,
    user: userWithoutPassword
  };
};
var getAllUsers = async () => {
  const users = await prisma.user.findMany();
  return users;
};
var getSingleUser = async (id) => {
  return await prisma.user.findUnique({
    where: { id }
  });
};
var getCurrentUser = async (id) => {
  const user = await prisma.user.findUnique({
    where: { id },
    select: {
      id: true,
      name: true,
      email: true,
      phone: true,
      avatar: true,
      role: true,
      status: true,
      address: true,
      city: true,
      country: true,
      emailVerified: true,
      provider: true,
      createdAt: true,
      updatedAt: true,
      lastLogin: true
    }
  });
  if (!user) {
    throw new Error("User not found");
  }
  return user;
};
var updateUser = async (id, payload) => {
  if (payload.password) {
    payload.password = await bcrypt.hash(payload.password, 10);
  }
  const { photoUrl, ...rest } = payload;
  const user = await prisma.user.update({
    where: { id },
    data: {
      ...rest,
      avatar: photoUrl
    },
    select: {
      id: true,
      name: true,
      email: true,
      phone: true,
      avatar: true,
      role: true,
      status: true,
      address: true,
      city: true,
      country: true,
      emailVerified: true,
      provider: true,
      createdAt: true,
      updatedAt: true,
      lastLogin: true
    }
  });
  return user;
};
var updatePassword = async (id, oldPassword, newPassword) => {
  const user = await prisma.user.findUnique({ where: { id } });
  if (!user) throw new Error("User not found");
  const isMatch = await bcrypt.compare(oldPassword, user.password);
  if (!isMatch) throw new Error("Old password is incorrect");
  const hashedPassword = await bcrypt.hash(newPassword, 10);
  const updatedUser = await prisma.user.update({
    where: { id },
    data: { password: hashedPassword },
    select: {
      id: true,
      name: true,
      email: true,
      phone: true,
      avatar: true,
      role: true,
      status: true,
      address: true,
      city: true,
      country: true,
      emailVerified: true,
      provider: true,
      lastLogin: true,
      createdAt: true,
      updatedAt: true
    }
  });
  return updatedUser;
};
var deleteUser = async (id) => {
  const user = await prisma.user.delete({
    where: { id }
  });
  return user;
};
var UserService = {
  registerUser,
  deleteUser,
  getAllUsers,
  loginUser,
  getSingleUser,
  updateUser,
  updatePassword,
  getCurrentUser
};

// src/app/shared/catchAsync.ts
var catchAsync = (fn) => {
  return async (req, res, next) => {
    try {
      await fn(req, res, next);
    } catch (error) {
      next(error);
    }
  };
};

// src/app/shared/sendResponse.ts
var sendResponse = (res, responseData) => {
  const { httpStatusCode, success, message, data } = responseData;
  res.status(httpStatusCode).json({
    success,
    message,
    data
  });
};

// src/app/modules/user/user.controller.ts
var registerUser2 = catchAsync(async (req, res) => {
  const payload = req.body;
  const result = await UserService.registerUser(payload);
  sendResponse(res, {
    httpStatusCode: 201,
    success: true,
    message: "user created successfully",
    data: result
  });
});
var loginUser2 = catchAsync(async (req, res) => {
  const result = await UserService.loginUser(req.body);
  sendResponse(res, {
    httpStatusCode: 200,
    success: true,
    message: "Login successful",
    data: result
  });
});
var getAllUsers2 = catchAsync(async (req, res) => {
  const result = await UserService.getAllUsers();
  sendResponse(res, {
    httpStatusCode: 200,
    success: true,
    message: "user fetched successfully",
    data: result
  });
});
var getSingleUser2 = catchAsync(async (req, res) => {
  const { id } = req.params;
  const result = await UserService.getSingleUser(id);
  sendResponse(res, {
    httpStatusCode: 200,
    success: true,
    message: "user fetched successfully",
    data: result
  });
});
var getCurrentUser2 = catchAsync(async (req, res) => {
  const id = req.user?.id;
  if (!id) {
    throw new Error("Unauthorized");
  }
  const result = await UserService.getCurrentUser(id);
  sendResponse(res, {
    httpStatusCode: 200,
    success: true,
    message: "user fetched successfully",
    data: result
  });
});
var updateUser2 = catchAsync(async (req, res) => {
  const { id } = req.params;
  const payload = req.body;
  const result = await UserService.updateUser(id, payload);
  sendResponse(res, {
    httpStatusCode: 200,
    success: true,
    message: "user updated successfully",
    data: result
  });
});
var changePassword = catchAsync(async (req, res) => {
  const { id } = req.params;
  const { oldPassword, newPassword } = req.body;
  const result = await UserService.updatePassword(
    id,
    oldPassword,
    newPassword
  );
  sendResponse(res, {
    httpStatusCode: 200,
    success: true,
    message: "Password updated successfully",
    data: result
  });
});
var deleteUser2 = catchAsync(async (req, res) => {
  const { id } = req.params;
  const result = await UserService.deleteUser(id);
  sendResponse(res, {
    httpStatusCode: 200,
    success: true,
    message: "user delete successfully",
    data: result
  });
});
var UserController = {
  registerUser: registerUser2,
  getAllUsers: getAllUsers2,
  deleteUser: deleteUser2,
  loginUser: loginUser2,
  getSingleUser: getSingleUser2,
  updateUser: updateUser2,
  changePassword,
  getCurrentUser: getCurrentUser2
};

// src/app/middleware/auth.ts
import jwt2 from "jsonwebtoken";
var auth = (...requiredRoles) => {
  return (req, res, next) => {
    try {
      const authHeader = req.headers.authorization;
      if (!authHeader) {
        return res.status(401).json({
          success: false,
          message: "You are not authorized"
        });
      }
      const token = authHeader.split(" ")[1];
      if (!token) {
        return res.status(401).json({
          success: false,
          message: "Invalid token format"
        });
      }
      const verifiedUser = jwt2.verify(token, envVars.JWT_SECRET);
      if (requiredRoles.length && !requiredRoles.includes(verifiedUser.role)) {
        return res.status(403).json({
          success: false,
          message: "Forbidden access"
        });
      }
      req.user = verifiedUser;
      next();
    } catch (error) {
      next(error);
    }
  };
};

// src/app/modules/user/user.route.ts
var router = Router();
router.post("/", UserController.registerUser);
router.post("/login", UserController.loginUser);
router.get("/", UserController.getAllUsers);
router.get(
  "/me",
  auth(Role.ADMIN, Role.SELLER, Role.CUSTOMER),
  UserController.getCurrentUser
);
router.get(
  "/:id",
  auth(Role.ADMIN, Role.SELLER, Role.CUSTOMER),
  UserController.getSingleUser
);
router.put(
  "/:id",
  auth(Role.SELLER, Role.CUSTOMER, Role.ADMIN),
  UserController.updateUser
);
router.put(
  "/:id/password",
  auth(Role.SELLER, Role.CUSTOMER, Role.ADMIN),
  UserController.changePassword
);
router.delete("/:id", auth(Role.ADMIN), UserController.deleteUser);
var UserRoute = router;

// src/app/routes/index.ts
var router2 = Router2();
router2.use("/users", UserRoute);
var routes_default = router2;

// src/app/modules/payment/payment.webhook.ts
import Stripe from "stripe";
var stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
var handleWebhook = async (req, res) => {
  const sig = req.headers["stripe-signature"];
  const endpointSecret = process.env.STRIPE_WEBHOOK_SECRET;
  let event;
  try {
    event = stripe.webhooks.constructEvent(req.body, sig, endpointSecret);
  } catch (err) {
    return res.status(400).send("Webhook Error");
  }
  if (event.type === "checkout.session.completed") {
    const session = event.data.object;
    await prisma.payment.create({
      data: {
        userId: session.metadata.userId,
        courseId: session.metadata.courseId,
        amount: session.amount_total / 100,
        currency: session.currency,
        status: session.payment_status,
        stripeSessionId: session.id
      }
    });
  }
  res.json({ received: true });
};

// src/app.ts
var app = express();
var corsOptions = {
  origin: [
    "http://localhost:3000",
    "https://delt-a-digivast-frontend.vercel.app",
    "https://deltadigivast.vercel.app",
    "https://www.deltadigivast.com"
  ],
  credentials: true,
  methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
  allowedHeaders: [
    "Content-Type",
    "Authorization",
    "Origin",
    "X-Requested-With",
    "Accept"
  ],
  optionsSuccessStatus: 204
};
app.use(cors(corsOptions));
app.use(express.urlencoded({ extended: true }));
app.post("/webhook", express.raw({ type: "application/json" }), handleWebhook);
app.use(express.json());
app.use("/api/v1", routes_default);
app.get("/", (req, res) => {
  res.status(200).json({
    message: "Server is running"
  });
});
app.use(globalErrorHandler);
app.use(notFound);
var app_default = app;

// src/server.ts
var bootstrap = () => {
  try {
    app_default.listen(envVars.PORT, () => {
      console.log(`\u{1F680} Server is running on http://localhost:${envVars.PORT}`);
    });
  } catch (error) {
    console.log(error);
  }
};
bootstrap();
